"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import setuptools

APP = ['engine.py']
DATA_FILES = [
    'dejavu16x16_gs_tc.png',
    'menu_background.png'
]
OPTIONS = {}

setuptools.setup(
    app=APP,
    name="Dragons_and_Dungeons",
    version="0.0.1",
    author="Frederico Bittencourt",
    author_email="fred.rbittencourt@gmail.com",
    packages=setuptools.find_packages(),
    install_requires=[
        'tcod'
    ],
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=[
        'py2app',
        'tcod'
    ],
)
